package com.sirma.itt.evgeni.comunication;

public enum MesageCommand {

	COMUNICATOR_CONECTING, COMUNICATOR_DISCONECTED, USER_CONECTED, USER_DISCONECTED, TEXT_MESAGE, USER_LOG_IN, USER_LOG_OUT, INVALID_USER_NAME
}
